"""add document pages

Revision ID: f9c70be32bf9
Revises: f966038dee4a
Create Date: 2026-08-24 20:43:27.183209

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f9c70be32bf9'
down_revision: str | Sequence[str] | None = 'f966038dee4a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(
        ["document_id"],
        ["documents.id"],
        ondelete="CASCADE",
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
    op.f("ix_document_pages_document_id"),
    "document_pages",
    ["document_id"],
    unique=False,
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    # ### end Alembic commands ###
